# Generated by Django 4.1.3 on 2022-11-15 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(150)])),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
