# Generated by Django 4.1.3 on 2022-11-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancebike',
            old_name='colour',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='balancebike',
            name='name',
        ),
        migrations.AddField(
            model_name='balancebike',
            name='custom_tag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='balancebike',
            name='edge_color',
            field=models.CharField(choices=[('Brown edge', 'Brown'), ('Blue edge', 'Blue'), ('Pink edge', 'Pink')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
