# Generated by Django 4.1.3 on 2022-11-17 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=1, validators=[django.core.validators.RegexValidator(code='nomatch', message='Телефонния номер трябва да съдържа точно 10 цифри', regex='^.{10}$')]),
            preserve_default=False,
        ),
    ]
