# Generated by Django 4.1.3 on 2022-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_colour_balancebike_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancebike',
            name='edge_color',
        ),
        migrations.AddField(
            model_name='balancebike',
            name='color',
            field=models.CharField(choices=[('Brown', 'Brown'), ('Blue', 'Blue'), ('Pink', 'Pink')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
