# Generated by Django 4.1.3 on 2022-11-17 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
