# Generated by Django 4.1.3 on 2022-11-16 09:57

import additionals.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_balancebike_edge_color_balancebike_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceBikeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Телефонния номер трябва да съдържа точно 10 цифри', regex='^.{10}$')])),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('address', models.TextField(max_length=40)),
            ],
        ),
    ]
