# Generated by Django 4.1.3 on 2022-11-17 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancebike',
            name='model',
            field=models.CharField(choices=[('Classic', 'Classic')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
