# Generated by Django 4.1.3 on 2022-11-17 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_balancebike_model_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='color',
            field=models.CharField(choices=[('Кафяв', 'Brown'), ('Син', 'Blue'), ('Розов', 'Pink')], max_length=15),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(150)]),
        ),
        migrations.CreateModel(
            name='OrderBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.balancebike')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.order')),
            ],
        ),
    ]
