# Generated by Django 4.1.3 on 2022-11-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_balancebike_quantity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderbike',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='orderbike',
            name='order',
        ),
        migrations.DeleteModel(
            name='CheckoutDetail',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderBike',
        ),
    ]
