# Generated by Django 4.1.3 on 2022-11-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
