# Generated by Django 4.1.3 on 2022-11-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_address_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработва се...', 'Обработва се...'), ('Изпратена', 'Изпратена'), ('Доставена', 'Доставена')], default='Pending', max_length=50),
        ),
    ]
