# Generated by Django 4.1.3 on 2022-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработва се', 'Pending'), ('Изпратена', 'Sent'), ('Доставена', 'Delivered'), ('Отказана', 'Canceled')], default='Обработва се', max_length=20),
        ),
    ]
