# Generated by Django 4.1.3 on 2022-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number_of_street',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='custom_tag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
