# Generated by Django 4.1.3 on 2022-11-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_address_number_of_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='number_of_street',
        ),
    ]
