# Generated by Django 4.1.3 on 2022-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_cart_created_at_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name_for_engraving',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Моля въведете ИМЕ за гравиране'),
        ),
    ]
