# Generated by Django 4.1.3 on 2022-11-28 07:24

import additionals.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_address_name_for_engraving'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=2, max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='name_for_engraving',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
