# Generated by Django 4.1.3 on 2022-12-08 09:19

import additionals.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), additionals.validators.name_has_only_letters], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name_for_engraving',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Име за гравиране'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Улица(квартал)'),
        ),
    ]
