# Generated by Django 4.1.3 on 2022-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_address_city_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancebike',
            name='custom_tag',
        ),
    ]
