# Generated by Django 4.1.3 on 2022-12-12 14:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_balancebike_custom_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Населено място'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name_for_engraving',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Име За Гравиране'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='color',
            field=models.CharField(choices=[('Кафяв', 'Brown'), ('Син', 'Blue'), ('Розов', 'Pink')], max_length=15, verbose_name='Цвят'),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Снимка'),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='model',
            field=models.CharField(choices=[('Класик', 'Classic'), ('Бъдещ модел', 'Future Models')], max_length=15, verbose_name='Модел'),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(179)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='balancebike',
            name='quantity_available',
            field=models.IntegerField(default=1, verbose_name='Налично количество на склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.address', verbose_name='Адрес за доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на поръчка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.balancebike', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработва се', 'Pending'), ('Изпратена', 'Sent'), ('Доставена', 'Delivered'), ('Отказана', 'Canceled')], default='Обработва се', max_length=20, verbose_name='Статус на поръчка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Потребител'),
        ),
    ]
