# Generated by Django 4.1.3 on 2022-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_alter_address_city_alter_address_name_for_engraving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name_for_engraving',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Име За Гравиране'),
        ),
    ]
