# Generated by Django 4.1.3 on 2022-12-14 09:15

import additionals.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_address_name_for_engraving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), additionals.validators.number_has_only_digits], verbose_name='Телефон'),
        ),
    ]
